# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0002_revocation_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='revocation_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ai', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('Ei', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_revocaed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ai',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ei',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
