# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0003_auto_20170425_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='revocation_requests',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
