# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0004_revocation_requests_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revocation_list',
            name='Ai',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='revocation_list',
            name='Ei',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
