# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0005_auto_20170425_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_revocaed',
            new_name='is_revoked',
        ),
    ]
